version: 2

sources:
  - name: staging
    database: daring-octane-409806
     # For postgres:
      #database: production
    schema: ny_taxi

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata_2019
      - name: yellow_tripdata_2019


models:
  - name: stg_green_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""
        tests:
          - unique:
              severity : warn
          - not_null :
              severity : warn
              

      - name: vendor_id
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: rate_code
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: airport_fee
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: string
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity : warn
              quote: FALSE

      - name: payment_type_descripted
        data_type: string
        description: ""

      - name: distance_between_service
        data_type: numeric
        description: ""

      - name: time_between_service
        data_type: int64
        description: ""

      - name: trip_type
        data_type: string
        description: ""

      - name: imp_surcharge
        data_type: numeric
        description: ""

      - name: pickup_location_id
        data_type: string
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity : warn

      - name: dropoff_location_id
        data_type: string
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity : warn

      - name: data_file_year
        data_type: int64
        description: ""

      - name: data_file_month
        data_type: int64
        description: ""
